[tool.black]
line-length = 120

[tool.isort]
profile = "black"
src_paths = ["modules", "download.py", "one_tweet.py", "photoprism.py"]

[tool.mypy]
warn_unused_configs = true
files = ["modules", "download.py", "one_tweet.py", "photoprism.py"]
